# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
a = torch.randn(size=(7, 7))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
b = torch.randn(size=(1, 7))
# Perform matrix multiplication 
res = torch.matmul(a, b.T)

res.shape

torch.Size([7, 1])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
torch.manual_seed(42)

# Create two random tensors
a = torch.randn(2, 3)
b = torch.randn(3, 2)

# Matrix multiply tensors
res = torch.matmul(a, b)
res.shape


torch.Size([2, 2])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [11]:
# Set random seed on the GPU
if torch.cuda.is_available():
    torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [20]:
# Set random seed
torch.manual_seed(42)

# Check for access to GPU
device = 'cuda:0' if torch.cuda.is_available() else 'cpu'

# Create two random tensors on GPU
X = torch.randn(size=(2, 3)).to(device)
y = torch.randn(size=(2, 3)).to(device)


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [21]:
# Perform matmul on tensor_A and tensor_B
res = torch.matmul(X, y.T)
res

tensor([[ 0.7695,  0.3487],
        [ 1.1390, -0.6898]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [22]:
# Find max
print(torch.max(res))
# Find min
print(torch.min(res))

tensor(1.1390, device='cuda:0')
tensor(-0.6898, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [23]:
# Find arg max
print(f'Argmax: {torch.argmax(res)}')

# Find arg min
print(f'Argmin: {torch.argmin(res)}')

Argmax: 2
Argmin: 3



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [36]:
# Set seed
torch.manual_seed(42)
torch.cuda.manual_seed(1234)

# Create random tensor
random_tensor1 = torch.randn(size=(1, 1, 1, 10))

# Remove single dimensions
random_tensor2 = random_tensor1.squeeze()
# random_tensor2 = random_tensor1.view(10)


# Print out tensors and their shapes
print(random_tensor1)
print(random_tensor2)

tensor([[[[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229, -0.1863,  2.2082,
           -0.6380,  0.4617,  0.2674]]]])
tensor([ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229, -0.1863,  2.2082, -0.6380,
         0.4617,  0.2674])
