In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# import cv2

In [3]:
print(torch.__version__)

2.1.1+cu121


#### Tensor

Naming convention:
* Scalers and verctor in lowercase
* and MATRIX and TENSORS should be in uppercase

In [4]:
# scaler tensor
scaler = torch.tensor(7)
print(scaler.ndim)
print(scaler.item())

0
7


In [5]:
# vector
vector = torch.tensor([3, 2])
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [6]:
# Matrix

MATRIX = torch.tensor([
    [1, 2],
    [3, 4]
])

print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[0:, 0:1])

tensor([[1, 2],
        [3, 4]])
2
torch.Size([2, 2])
tensor([[1],
        [3]])


In [7]:
# Tensor

TENSOR = torch.tensor([[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]])

# print(TENSOR)
# print(TENSOR.ndim)
# print(TENSOR.shape) 

# TENSOR[0:, 0:, 0:1]

TENSOR2 = torch.tensor([
    [
        [1, 2, 2],
        [2, 3, 4],
        [4, 5, 6]
    ],
    [
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]
    ],
    [
        [7, 8, 9],
        [1, 2, 3],
        [10, 11, 12]
    ],
    [
        [3, 2, 1],
        [7, 6, 8],
        [0, 1, 1]
    ]
])

print(TENSOR2.shape)

torch.Size([4, 3, 3])


In [8]:
# numpy array to tensor

np_arr = np.array([
    [
        [1, 2, 2],
        [2, 3, 4],
        [4, 5, 6]
    ],
    [
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]
    ],
    [
        [7, 8, 9],
        [1, 2, 3],
        [10, 11, 12]
    ],
    [
        [3, 2, 1],
        [7, 6, 8],
        [0, 1, 1]
    ]
])

tnsr = torch.as_tensor(np_arr)

print(type(np_arr))
print(type(tnsr))

torch.zeros([3, 2])
cuda0 = torch.device('cuda:0')
cuda_tens = torch.ones([2, 4], dtype=torch.float64, device=cuda0)

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [9]:
x = torch.tensor([
    [1, -1],
    [1, 1]
], dtype=torch.float16, requires_grad=True)
out = x.pow(2).sum()
out.backward()
x = x.grad
# transpose
x.T

# stored on CPU/GPU
print(cuda_tens.is_cuda)
print(x.is_cuda)

print('device:cuda:- ', cuda_tens.device)
print('device:cpu:-', x.device)


True
False
device:cuda:-  cuda:0
device:cpu:- cpu


Random tensors

Random tensors are important because many neural networks lears is that they starts with tensors full of random numbers and then adjust those random numbers to better represent the data

`starts with random numbers => look at data => update random numbers => look at data => update random numbers`

In [10]:
random_tensor = torch.rand(3, 2)

# create a random tensor with 
# similar shape to an image tensor
# random_image_tensor = torch.rand(size=(224, 224, 3))
random_image_tensor = torch.rand(size=(3, 224, 224))

# random_image_tensor.shape, random_image_tensor.ndim
# random_image_tensor

In [11]:
# zeros and ones
zeros = torch.zeros(size=(3, 2))

ones = torch.ones(size=(2, 3))
ones.dtype

torch.float32

In [12]:
# creating a range of tensors and tensors-like

one_to_ten = torch.arange(start=0, end=100, step=10)

# tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Tensors dtypes

**Note:** Tensor data type is one of 3 big errors we will run into pytorch and deep learning:
1. Tensors not right datatype
2. tensors not right shape
3. tensors not on the right device

In [13]:
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None, # datatype 
    device=None, # what device is your tensor on
    requires_grad=False # weather or not to track gradients with this tensor operations
)
print(float_32_tensor.dtype)
# convert datatype
float_16_tensor = float_32_tensor.type(torch.float16)
print(float_16_tensor.dtype)


torch.float32
torch.float16


#### Getting information from tensors
### Attributes

In [14]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)

float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

1. Tensors not right datatype -> get datatype => `tensor.dtype`
2. tensors not right shape -> get shape => `tensor.shape`
3. tensors not on the right device -> get device => `tensor.device`

In [15]:
some_tensor = torch.rand(size=(3, 4))
print(some_tensor)

print(f'Datatype: {some_tensor.dtype}')
print(f'Shape: {some_tensor.shape}')
print(f'Device: {some_tensor.device}')

tensor([[0.1923, 0.5460, 0.2613, 0.0690],
        [0.3582, 0.4253, 0.8554, 0.4674],
        [0.0105, 0.8474, 0.5725, 0.3537]])
Datatype: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


#### Manipulating / Operations
* Addition
* Subtraction
* Multiplication ( element-wise )
* Division
* Matrix multiplication


In [16]:
# tnsr = torch.tensor([1, 2, 3])

tnsr = torch.rand(100)
add_tnsr = tnsr + 10

mul_tnsr = tnsr * 10

sub_tnsr = tnsr - 10

# built-in function
torch.mul(tnsr, 10)

tensor([7.3549, 0.6682, 8.7464, 2.8392, 7.6221, 8.9171, 6.9065, 7.4658, 2.0944,
        7.9536, 2.8469, 9.3514, 0.7830, 0.0850, 0.4527, 3.1551, 1.0490, 3.2875,
        3.6747, 3.6624, 3.1205, 2.8625, 4.5985, 2.0499, 7.9096, 1.1088, 6.0823,
        3.3671, 3.4450, 4.4622, 3.5299, 7.6801, 2.6881, 2.3121, 4.7407, 6.3635,
        3.7940, 2.4353, 6.0776, 4.4257, 9.5552, 5.8736, 3.4084, 3.5748, 8.6090,
        7.6266, 5.3818, 2.3725, 5.2328, 7.7907, 0.5093, 9.4815, 5.9960, 7.0213,
        4.8803, 1.2913, 4.9065, 2.5052, 6.6224, 0.2779, 4.5878, 2.5822, 6.0590,
        4.6002, 4.7564, 5.7544, 2.2262, 7.3875, 7.8516, 5.7462, 8.1783, 0.1483,
        9.1482, 3.2953, 0.4759, 6.9969, 1.2803, 4.7731, 5.9085, 3.1990, 1.6848,
        5.2371, 0.9504, 7.4589, 0.7487, 3.6532, 0.7607, 5.1274, 4.4371, 9.6762,
        3.6466, 8.8887, 5.6142, 9.7533, 6.2532, 7.5173, 5.0662, 2.0869, 8.0539,
        7.0805])

#### Matrix multiplication

1. element-wise multiplication
2. matrix multiplication (dot product)

In [17]:
print(tnsr ,'*', tnsr)
print(f'equals: {tnsr*tnsr}')

# matrix multiplication
torch.matmul(tnsr, tnsr)

tensor([0.7355, 0.0668, 0.8746, 0.2839, 0.7622, 0.8917, 0.6906, 0.7466, 0.2094,
        0.7954, 0.2847, 0.9351, 0.0783, 0.0085, 0.0453, 0.3155, 0.1049, 0.3288,
        0.3675, 0.3662, 0.3121, 0.2863, 0.4599, 0.2050, 0.7910, 0.1109, 0.6082,
        0.3367, 0.3445, 0.4462, 0.3530, 0.7680, 0.2688, 0.2312, 0.4741, 0.6363,
        0.3794, 0.2435, 0.6078, 0.4426, 0.9555, 0.5874, 0.3408, 0.3575, 0.8609,
        0.7627, 0.5382, 0.2372, 0.5233, 0.7791, 0.0509, 0.9482, 0.5996, 0.7021,
        0.4880, 0.1291, 0.4907, 0.2505, 0.6622, 0.0278, 0.4588, 0.2582, 0.6059,
        0.4600, 0.4756, 0.5754, 0.2226, 0.7388, 0.7852, 0.5746, 0.8178, 0.0148,
        0.9148, 0.3295, 0.0476, 0.6997, 0.1280, 0.4773, 0.5909, 0.3199, 0.1685,
        0.5237, 0.0950, 0.7459, 0.0749, 0.3653, 0.0761, 0.5127, 0.4437, 0.9676,
        0.3647, 0.8889, 0.5614, 0.9753, 0.6253, 0.7517, 0.5066, 0.2087, 0.8054,
        0.7081]) * tensor([0.7355, 0.0668, 0.8746, 0.2839, 0.7622, 0.8917, 0.6906, 0.7466, 0.2094,
        0.7954, 0.284

tensor(29.6050)

In [18]:
import time
st = time.time()
val = 0
for i in range(len(tnsr)):
    val += tnsr[i] * tnsr[i]

print(val)
print(f'{round(((time.time() - st) * 10**3), 500)}\'ms')

st = time.time()

mat_mul = torch.matmul(tnsr, tnsr)
print(mat_mul)

print(f'{round(((time.time() - st) * 10**3), 500)}\'ms')

tensor(29.6050)
2.992391586303711'ms
tensor(29.6050)
0.9973049163818359'ms


In [19]:
import time

st = time.time()

mat_mul = torch.matmul(tnsr, tnsr)
print(mat_mul)

print(f'{round(((time.time() - st) * 10**3), 120)}\'ms')

tensor(29.6050)
0.9984970092773438'ms


In [20]:
A = torch.rand(size=(30, 5)) # A's column
B = torch.rand(size=(5, 32)) # b's row must be same

matrix_mul = torch.matmul(A, B)
print(matrix_mul.shape)

torch.Size([30, 32])


In [27]:
A = torch.rand(size=(7, 80))
B = torch.rand(size=(80, 3))

# print(f' {A.shape} \n\t\tx\n {B.shape} \n-----------------------------------\n {torch.matmul(A, B).shape}')

# check shape
def check_and_print(A, B):
    if len(A.shape) != 2 or len(B.shape) != 2:
        print('Please enter matrix....')
        exit(1)
    else:
        # if A.shape[1] != B.shape[0]:
        #     print('Please enter a VALID matrix....1')
        #     quit()
        # mat_mul = torch.matmul(A, B)
        try:
            mat_mul = torch.matmul(A, B)
            print(f' {A.shape} \n\t\tx\n {B.shape} \n-----------------------------------\n result will be in\n {mat_mul.shape} shape')
        except RuntimeError:
            # quit()
            print('Please enter a VALID matrix....2')

check_and_print(A, B)


 torch.Size([7, 80]) 
		x
 torch.Size([80, 3]) 
-----------------------------------
 result will be in
 torch.Size([7, 3]) shape


In [46]:
A = torch.rand(size=(50, 2), dtype=torch.float32)
B = torch.rand(size=(20, 2), dtype=torch.float32)

# torch.matmul(A, B).shape
# matrix multiplication will work when tensor_B is TRANSPOSED
torch.matmul(A, B.T).shape

torch.Size([50, 20])